[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install",
  "npm install --prefix backend",
  "npm install --prefix frontend"
]

[phases.build]
cmds = ["npm run vps-build"]

[start]
cmd = "npm run vps-start"
